
---
services:
  columns:
  - id
  - published
  - name
  - short_description
  - full_description
  - avatar_file_name
  - avatar_content_type
  - avatar_file_size
  - avatar_updated_at
  - created_at
  - updated_at
  - sort_id
  - services_page_id
  - avatar_alt
  - slug
  - avatar_file_name_fallback
  records: 
  - - 1
    - true
    - "Логотип та фірмовий стиль"
    - "<p>Одним з ключових напрямків роботи нашої студії є розробка логотипів (символи,
      шрифтові написи) та фірмових стилів. Ми розробляємо продумані символи з врахуванням
      специфіки діяльності, цільової аудиторії та позиціонування. А букви в логотипах
      ми малюємо вручну, для того щоб Ваш логотип був дійсно професійним та унікальним.</p>\r\n<p>Ваш
      новий фірмовий стиль розпочнеться з колористики та шрифтових рішень, які будуть
      вдало застосовані в акцидентній продукції (фірмовий бланк, візитка, папка, конверти,
      сувенірна продукція, службовий автотранспорт, вивіски тощо). Все це ми оформимо
      в професійний бренд бук (корпоративні скерування) щоб ніхто нічого не загубив
      і не забув :)</p>"
    - ''
    - logo-design-corporate-identity.jpg
    - image/jpeg
    - 50519
    - '2015-04-14 11:44:20.999155'
    - '2013-03-27 23:01:11.126810'
    - '2015-06-23 11:09:11.429936'
    - 1
    - 
    - ''
    - logotip-ta-firmoviy-stil
    - logo-design-corporate-identity.jpg
  - - 2
    - true
    - "Упаковка і етикетка"
    - "<p>Ми любимо класні етикетки та упаковки, а ще більше ми любимо їх розробляти.
      Пляшки, пакети, коробки, блістери – ми розробимо для Вас будь який вид упаковки!
      Але, найбільше задоволення нам приносить, коли результат продається на поличках
      супермаркетів.</p>"
    - ''
    - packaging-design-label.jpg
    - image/jpeg
    - 45804
    - '2015-04-14 11:44:22.275997'
    - '2013-03-29 00:35:10.650514'
    - '2015-06-23 12:35:26.685421'
    - 2
    - 
    - ''
    - upakovka-i-etiketka
    - packaging-design-label.jpg
  - - 3
    - true
    - "Рекламні POS матеріали"
    - "<p>Хорошому товару потрібна хороша реклама! Ми допоможемо Вам збільшити продажі,
      завоювати нові ринки та нових клієнтів за допомогою продуманої та креативної
      реклами. Від флаєру до білл борду все виконаємо  з врахуванням цільової аудиторії,
      особливостей товару та Вашого бюджету. </p>"
    - ''
    - Print-advertising.jpg
    - image/jpeg
    - 19911
    - '2015-04-14 11:44:23.443160'
    - '2013-03-29 00:35:52.021839'
    - '2015-06-23 13:24:38.197121'
    - 5
    - 
    - ''
    - reklamni-pos-materiali
    - Print-advertising.jpg
  - - 4
    - true
    - "Постери (афіші)"
    - "Вже давно наша студія зарекомендувала себе, як одна з найкращих в Україні у
      сфері розробки афіш для вечірок в нічних клубах, концертів та будь яких інших
      заходів, що потребують гарного «обличчя»."
    - ''
    - poster-design-print.jpg
    - image/jpeg
    - 51520
    - '2015-04-14 11:44:24.607465'
    - '2013-03-29 00:36:51.739163'
    - '2015-06-23 14:31:50.661619'
    - 7
    - 
    - ''
    - posteri-afishi
    - poster-design-print.jpg
  - - 5
    - true
    - "Новорічні календарі та листівки"
    - "<p>Хорошому товару потрібна хороша реклама! Ми допоможемо Вам збільшити продажі,
      завоювати нові ринки та нових клієнтів за допомогою продуманої та креативної
      реклами. Від флаєру до білл борду все виконаємо  з врахуванням цільової аудиторії,
      особливостей товару та Вашого бюджету. </p>"
    - ''
    - design-calendar-christmas-cards.jpg
    - image/jpeg
    - 31373
    - '2015-04-14 11:44:25.753790'
    - '2013-03-29 00:37:22.448393'
    - '2015-06-23 14:48:38.505895'
    - 8
    - 
    - ''
    - novorichni-kalendari-ta-listivki
    - design-calendar-christmas-cards.jpg
  - - 6
    - true
    - "Розробка веб-сайтів"
    - "Ми розробляємо не просто гарні веб сайти, а такі які виконують поставлені задачі.
      Розробляємо їх ми по сучасним технологіям HTML5, CSS3, Ruby on Rails. А дизайн
      адаптований під різні мобільні пристрої, планшети та деск-топ комп'ютери (Responsive
      design)."
    - ''
    - web-development.jpg
    - image/jpeg
    - 42365
    - '2015-04-14 11:44:26.912098'
    - '2013-05-03 13:09:12.089529'
    - '2015-06-24 12:48:52.156846'
    - 3
    - 
    - ''
    - rozrobka-veb-saytiv
    - web-development.jpg
  - - 7
    - true
    - "Мобільні додатки"
    - "Розробляємо мобільні додатки для iOS та Android систем. Велику увагу приділяємо
      \ зручності користування додатком, розробці інтерфейсу та чистоті коду."
    - ''
    - mobile-application-development.jpg
    - image/jpeg
    - 26384
    - '2015-04-14 11:44:28.130250'
    - '2013-05-03 13:26:13.949855'
    - '2015-06-24 13:11:20.851737'
    - 4
    - 
    - ''
    - mobilni-dodatki
    - mobile-application-development.jpg
  - - 8
    - true
    - "Буклети і каталоги"
    - "Презентувати свою продукцію за допомогою гарного буклету чи каталогу. Використовуємо
      складні поліграфічні технології для досягнення максимального ефекту."
    - ''
    - design-leaflet-and-catalog.jpg
    - image/jpeg
    - 45545
    - '2015-04-14 11:44:29.314214'
    - '2013-05-03 13:40:17.064350'
    - '2015-06-25 08:46:35.495964'
    - 6
    - 
    - "Буклети і каталоги"
    - bukleti-i-katalogi
    - design-leaflet-and-catalog.jpg
